name: dora_check

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Test another repo
        uses: eBerdnA/deployment-frequency@main
        with:
          workflows: 'CI'
          owner-repo: 'eBerdnA/pyjou'
          default-branch: 'main'
          number-of-days: 30