name: dora_check

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Test another repo
        uses: samsmithnz/deployment-frequency@1.0.0
        with:
          workflows: 'parent2'
          owner-repo: 'eBerdnA/workflow-demo'
          default-branch: 'main'
          number-of-days: 30