name: self_dora_check

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Test another repo
        uses: eBerdnA/deployment-frequency@github-app2
        with:
          workflows: 'dora_check'
